apiVersion: v1
kind: Pod
metadata:
  name: sudoku
  labels:
    app: sudoku
spec:
  containers:
    - image: docker.io/richardeigenmann/sudoku:1.1
      name: sudoku
      ports:
        - containerPort: 80
          name: http
          protocol: TCP